import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { getGeo } from "geoplugin";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import * as ga from "../lib/google-analytics/index.js";

const Home: NextPage = () => {
  const customEventCall = () => {
    ga.customEvent({
      action: `Location`,
      "country": `${location}` 
    });
  };

  const [location, setLocation] = useState("")

  useEffect(() => {
    getGeo()
      .then((response:any) => setLocation(response.countryCode)) // handle success
      .catch((error:any) => console.log(error)) // handle error
      .then(() => {});
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>Hello World</h3>
        <Link href={"/about"}>
          <a>About</a>
        </Link>
        <Link href={"/contact"}>
          <a>Contact</a>
        </Link>
        <button onClick={customEventCall}> Custom event Call </button>
      </main>
    </div>
  );
};

export default Home;
